---

- name: 'ensure .ssh dir exists for ansible user'
  file: path=/home/{{ ansible_user }}/.ssh owner={{ ansible_user }} group={{ ansible_user }} mode=0700

- name: 'copy ssh keys to control host'
  become: no
  copy: src={{ item }} dest=/home/{{ ansible_user }}/.ssh mode=0600
  with_items:
    - id_rsa
    - id_rsa.pub
    - id_rsa-cert.pub

- name: 'copy test inventory to control host'
  become: yes
  copy: src=hosts dest=/home/{{ ansible_user }}/inventory.ini mode=0644

- name: 'copy test config to control host'
  become: yes
  copy: src=../../../ansible.cfg dest=/home/{{ ansible_user }}/ansible.cfg mode=0644

- name: 'copy playbook to control host'
  become: no
  copy: src=playbook.yml dest=/home/{{ ansible_user }}/playbook.yml mode=0700


